### ISSUE TITLE
Template Validation

### ISSUE THREAD

**Issue by Giaco9** [lusentis/dawson#17]
Could be useful call validate-template before start update or create stack.

Doc
http://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html

**Comment by lusentis** [comment]
I think that creating a ChangeSet works for now. The ValidateTemplate API won't catch many errors, just syntax errors (which are anyway limited because the JSON object is generated by `dawson`).

> The aws cloudformation validate-template command is designed to check only the syntax of your template. It does not ensure that the property values you have specified for a resource are valid for that resource. Nor does it determine the number of resources that will exist when the stack is created.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-validate-template.html

Additionally, I think in the future we'll make extensive use of nested templates, and we cannot check for the validity of each of them.

I'm closing for now.
